package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"time"

	"posts-comments-1/graph/model"
	"posts-comments-1/internal/domain"

	"github.com/google/uuid"
)

// CreatedAt is the resolver for the createdAt field.
func (r *commentResolver) CreatedAt(ctx context.Context, obj *domain.Comment) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// CreatePost is the resolver for the createPost field.
func (r *postResolver) CreatedAt(ctx context.Context, obj *domain.Post) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// SetCommentsAllowed is the resolver for the setCommentsAllowed field.
func (r *mutationResolver) SetCommentsAllowed(ctx context.Context, postID uuid.UUID, allowed bool) (*domain.Post, error) {
	p, err := r.Storage.GetPost(postID)
	if err != nil {
		return nil, err
	}

	p.CommentsAllowed = allowed
	if err := r.Storage.UpdatePost(*p); err != nil {
		return nil, err
	}

	return p, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*domain.Comment, error) {
	c := domain.Comment{
		ID:        uuid.New(),
		PostID:    input.PostID,
		ParentID:  input.ParentID,
		Content:   input.Content,
		CreatedAt: time.Now(),
	}

	if err := r.Storage.CreateComment(c); err != nil {
		return nil, err
	}
	return &c, nil
}

func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*domain.Post, error) {
	p := domain.Post{
		ID:              uuid.New(),
		Title:           input.Title,
		Content:         input.Content,
		CommentsAllowed: input.CommentsAllowed,
		CreatedAt:       time.Now(),
	}

	if err := r.Storage.CreatePost(p); err != nil {
		return nil, err
	}
	return &p, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit int32, offset int32) ([]*domain.Post, error) {
	posts, err := r.Storage.ListPosts(int(limit), int(offset))
	if err != nil {
		return nil, err
	}

	out := make([]*domain.Post, 0, len(posts))
	for i := range posts {
		p := posts[i]
		out = append(out, &p)
	}
	return out, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id uuid.UUID) (*domain.Post, error) {
	return r.Storage.GetPost(id)
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID uuid.UUID, limit int32, offset int32) ([]*domain.Comment, error) {
	comments, err := r.Storage.GetComments(postID, int(limit), int(offset))
	if err != nil {
		return nil, err
	}

	out := make([]*domain.Comment, 0, len(comments))
	for i := range comments {
		c := comments[i]
		out = append(out, &c)
	}
	return out, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
