package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"posts-comments-1/graph/model"
	"posts-comments-1/internal/domain"
	"time"

	"github.com/google/uuid"
)

// CreatedAt is the resolver for the createdAt field.
func (r *commentResolver) CreatedAt(ctx context.Context, obj *domain.Comment) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*domain.Post, error) {
	p := domain.Post{
		ID:              uuid.New(),
		Title:           input.Title,
		Content:         input.Content,
		CommentsAllowed: input.CommentsAllowed,
		CreatedAt:       time.Now(),
	}

	if err := r.Storage.CreatePost(p); err != nil {
		return nil, err
	}
	return &p, nil
}

// SetCommentsAllowed is the resolver for the setCommentsAllowed field.
func (r *mutationResolver) SetCommentsAllowed(ctx context.Context, postID uuid.UUID, allowed bool) (*domain.Post, error) {
	p, err := r.Storage.GetPost(postID)
	if err != nil {
		return nil, err
	}

	p.CommentsAllowed = allowed
	if err := r.Storage.UpdatePost(*p); err != nil {
		return nil, err
	}

	return p, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*domain.Comment, error) {
	c := domain.Comment{
		ID:        uuid.New(),
		PostID:    input.PostID,
		ParentID:  input.ParentID,
		Content:   input.Content,
		CreatedAt: time.Now(),
	}

	if err := r.Storage.CreateComment(c); err != nil {
		return nil, err
	}
	r.publishComment(&c)
	return &c, nil
}

func (r *Resolver) publishComment(c *domain.Comment) {
	r.mu.Lock()
	defer r.mu.Unlock()

	subs := r.subscribers[c.PostID]
	for _, ch := range subs {
		select {
		case ch <- c:
		default:
		}
	}
}

// CreatePost is the resolver for the createPost field.
func (r *postResolver) CreatedAt(ctx context.Context, obj *domain.Post) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit int32, offset int32) ([]*domain.Post, error) {
	posts, err := r.Storage.ListPosts(int(limit), int(offset))
	if err != nil {
		return nil, err
	}

	out := make([]*domain.Post, 0, len(posts))
	for i := range posts {
		p := posts[i]
		out = append(out, &p)
	}
	return out, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id uuid.UUID) (*domain.Post, error) {
	return r.Storage.GetPost(id)
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID uuid.UUID, limit int32, offset int32) ([]*domain.Comment, error) {
	comments, err := r.Storage.GetComments(postID, int(limit), int(offset))
	if err != nil {
		return nil, err
	}

	out := make([]*domain.Comment, 0, len(comments))
	for i := range comments {
		c := comments[i]
		out = append(out, &c)
	}
	return out, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID uuid.UUID) (<-chan *domain.Comment, error) {
	ch := make(chan *domain.Comment, 16)

	r.mu.Lock()
	r.nextSubID++
	id := r.nextSubID

	if r.subscribers == nil {
		r.subscribers = make(map[uuid.UUID]map[int]chan *domain.Comment)
	}
	if r.subscribers[postID] == nil {
		r.subscribers[postID] = make(map[int]chan *domain.Comment)
	}
	r.subscribers[postID][id] = ch
	r.mu.Unlock()

	go func() {
		<-ctx.Done()

		r.mu.Lock()
		if m := r.subscribers[postID]; m != nil {
			if subCh, ok := m[id]; ok {
				close(subCh)
				delete(m, id)
			}
			if len(m) == 0 {
				delete(r.subscribers, postID)
			}
		}
		r.mu.Unlock()
	}()

	return ch, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
