// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type CreateCommentInput struct {
	PostID   uuid.UUID  `json:"postID"`
	ParentID *uuid.UUID `json:"parentID,omitempty"`
	Content  string     `json:"content"`
}

type CreatePostInput struct {
	Title           string `json:"title"`
	Content         string `json:"content"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
